### ISSUE TITLE
不用mycat了？   

### ISSUE THREAD

**Issue by gaotuan** [jevislee/laravelgenerator#1]
Closed #2126.改用proxysql了

**Comment by jevislee** [comment]
是的,根本不能用,只是为了读写分离的话,可以用proxysql

**Comment by gaotuan** [comment]
是的，如果只有读写分离的需求的话  proxysql 足够了。 mycat我个人觉得主要还是用在分库分表

**Comment by jevislee** [comment]
数据量太大需要分库分表的话可以用tidb

**Comment by gaotuan** [comment]
tidb我们也调研了，目前还不太敢在生产上用。业务场景简单的话 我们准备用mycat

**Comment by gaotuan** [comment]
看了一圈分库分表的中间件

**Comment by jevislee** [comment]
https://tech.meituan.com/2018/11/22/mysql-pingcap-practice.html
美团现在都在线上环境用tidb了,这个最好直接选择分布式数据库
